title: Moon's Linux Knowledge Base
description: A guide to getting started with Linux
theme: just-the-docs

url: https://signalno11.github.io
repository: signalno11/knowledge

search_enabled: true
enable_copy_code_button: true
heading_anchors: true

aux_links:
  "PC Help Hub on Discord": "https://discord.gg/pchh"
aux_links_new_tab: true

back_top_top: true

color_scheme: dark

callouts:
  important:
    title: Important
    color: purple
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
